name=Mti_Serial
version=1.1.0
author=kkfranco98
maintainer=kkfranco98
sentence=Minimal Arduino library for MTi devices over serial
paragraph=Provides a lightweight Xbus parser and basic support for Euler angles, acceleration, gyro data and common MTi serial commands
category=Communication
architectures=*
license=MIT
url=https://github.com/kkfranco98/Mti_Serial